### ISSUE TITLE
文件名包含括号（）会报参数错误

### ISSUE THREAD

**Issue by XiaoGeMa** [lorniu/emacs-baidupan#1]
在进行增删查改时，如果要操作的文件名包括括号，会报参数错误

> if: [2] 参数错误

**Comment by lorniu** [comment]
你再详细说下问题产生的场景，我刚试了将一个文件改名为 `（）hel˃d,j的，飞机lo-(dkfj)-（dkfj ）aaa.js` 没报错。

**Comment by XiaoGeMa** [comment]
又在emacs -Q下试了试，没问题，应该还是环境（ivy）的问题。

**Comment by lorniu** [comment]
你可以将你的操作描述下，包括文件名由哪个变成哪个，出了什么状况。

这有可能是环境问题，也可能是 BUG。如果是 BUG 我看能不能复现。

**Comment by lorniu** [comment]
你更下代码再试试吧。

**Comment by XiaoGeMa** [comment]
emacs -Q 加载dupan.el后，将百度网盘  我的资源 下 “唐诗三百首（许译中国经典诗文集）（中英对照）.pdf” 拷贝到 网盘根目录下报错。
再有，从本地往网盘上拷贝大文件（1G 左右）时emacs僵死很久，查进程看到emacs已经读取了几十G的硬盘信息。

**Comment by XiaoGeMa** [comment]
> 你更下代码再试试吧。

问题还在。
试了一下，好像是中文目录的问题，
emacs -Q 将 网盘根目录下的文件拷到 我的资源目录，会显示拷贝成功，但实际上没有文件产生。

**Comment by lorniu** [comment]
> emacs -Q 将 网盘根目录下的文件拷到 我的资源目录，会显示拷贝成功，但实际上没有文件产生。

这个单纯就是个BUG，已修复

> 将百度网盘 我的资源 下 “唐诗三百首（许译中国经典诗文集）（中英对照）.pdf” 拷贝到 网盘根目录下报错。

这个出错的原因不是因为中文，而是因为文件名太长...百度没有提供根据文件名获取文件基本信息的 API，只能通过搜索的方式曲线实现，这样如果文件名过长就发生问题。后面看看能不能换一种更好的方式。

**Comment by lorniu** [comment]
> 将百度网盘 我的资源 下 “唐诗三百首（许译中国经典诗文集）（中英对照）.pdf” 拷贝到 网盘根目录下报错。

这个也已经修复。请更新代码后再试试看看有没有问题。

**Comment by XiaoGeMa** [comment]
> > 将百度网盘 我的资源 下 “唐诗三百首（许译中国经典诗文集）（中英对照）.pdf” 拷贝到 网盘根目录下报错。
> 
> 这个也已经修复。请更新代码后再试试看看有没有问题。

可以了
