### ISSUE TITLE
文件夹内容异常

### ISSUE THREAD

**Issue by XiaoGeMa** [lorniu/emacs-baidupan#2]
鉴赏课+名画鉴赏课
鉴赏课 名画鉴赏课
这两个文件夹在同一个目录下，第一个文件夹下内容异常，和第二个文件夹下内容变成一样的了。
貌似是'+' 和 ' '转码都转成％20了，加号应该是%2B
用dupan-browser打开带加号的文件夹显示也是％20

**Comment by lorniu** [comment]
已修正，请测试。

**Comment by XiaoGeMa** [comment]
> 已修正，请测试。

OK了
