### ISSUE TITLE
dired mark之后移动多个文件夹时有时会返回12号错误

### ISSUE THREAD

**Issue by XiaoGeMa** [lorniu/emacs-baidupan#4]
继续移动往往可以正常把剩下的全部或部分文件夹转移。

**Comment by lorniu** [comment]
代码已修改。

多个文件同时移动也可能触发 `请求过于频繁，稍后再试` 的错误。这种情况，没办法，只能执行类似如下代码，让操作结束后等待若干时间:

```elisp
(cl-defmethod dupan-req :after ((_ (eql 'move)) from to)
  (sleep-for 3)) ; 让当前调用 (move) 结束后等待 3 秒钟
```

**Comment by XiaoGeMa** [comment]
> 代码已修改。
> 
> 多个文件同时移动也可能触发 `请求过于频繁，稍后再试` 的错误。这种情况，没办法，只能执行类似如下代码，让操作结束后等待若干时间:
> 
> ```emacs-lisp
> (cl-defmethod dupan-req :after ((_ (eql 'move)) from to)
>   (sleep-for 3)) ; 让当前调用 (move) 结束后等待 3 秒钟
> ```

改完之后情况好多了，我试着整理了几百G文件，没有严重问题了。
不过文件夹多的情况下还是时不时会出现 `请求过于频繁，稍后再试` 或者`参数错误`的故障。
遇到上述情况后继续move还是可以进行下去的，直到完全成功。
鉴于此种情况，有没有可能在遇到错误时等待几秒继续move，直到成功或者错误次数过多超时。

**Comment by lorniu** [comment]
> 有没有可能在遇到错误时等待几秒继续move，直到成功或者错误次数过多超时。

这个可能需要修改 `dired-do-rename` 的源码，不好实现。另外，百度抛错误的规律不透明，处理起来比较难受。总之，就是解决这个问题的成本高、不值得（毕竟批量移动不算频繁使用的日常功能，无伤大雅）。

所以当下的话，要么出错了自己等下重试，要么在多文件移动的适合增加等待时间，类似:
```elisp
(cl-defmethod dupan-req :after ((_ (eql 'move)) from to) (sleep-for 一个更大的等待时间))
```

后面如果有时间再考虑深度优化吧。当然，欢迎提交补丁。

**Comment by XiaoGeMa** [comment]
谢谢了。加上等待3秒后好多了，move 80个文件只停两三次了，不影响使用了。
这个包太好用了，我平时主要整理花的时间多些，百度官方客户端做的实在问题太多，操作及其复杂。有空我研究研究dired-do-rename，看看能不能打个补丁。

**Comment by lorniu** [comment]
> 有空我研究研究dired-do-rename，看看能不能打个补丁

百度 API 支持批量移动，如果修改了 dire-do-rename 相关逻辑，这种移动多个文件只需要一个请求就能完成的

**Comment by XiaoGeMa** [comment]
> 

看来一个请求是正路，一劳永逸地解决频繁操作的问题。

**Comment by XiaoGeMa** [comment]
看了dired的代码，找到dired-get-marked-files，不过对elisp还不太熟，不知道怎么来用。
提个建议，看看能不能绕过dired接口,直接把多文件copy，rename，delete单请求的加进去。

**Comment by lorniu** [comment]
你说的我手痒，干脆就实现了一下。麻烦测试。

**Comment by XiaoGeMa** [comment]
> 你说的我手痒，干脆就实现了一下。麻烦测试。

太棒了！！！
