### ISSUE TITLE
增加 aria2 下载支持

### ISSUE THREAD

**Issue by jiacai2050** [lorniu/emacs-baidupan#7]
aria2 支持通过 jsonrpc 协议添加下载任务
https://aria2.github.io/manual/en/html/aria2c.html?highlight=jsonrpc#methods
```sh
curl --location --request POST 'localhost:6800/jsonrpc' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "qwer",
    "method": "aria2.addUri",
    "params": [
        ["http://example.com"]]} '
```
要是能和这个插件结合起来就好了。

**Comment by lorniu** [comment]
我觉得没必要。如果真想使用 aria2c 或其他第三方工具下载某个文件，只要在 dired 中使用 `dupan-browser` 进入到 web 页面，然后用浏览器安装的插件下载，其实也麻烦不了多少。

如果想让文件的复制、移动也使用 aria2c，那有点不好搞。毕竟 aria2c 的下载是异步的。

**Comment by jiacai2050** [comment]
那等我有空尝试加下吧，对我来说还挺有用的

> 只要在 dired 中使用 dupan-browser 进入到 web 页面

这个插件的优势就是不用打开浏览器🤪

**Comment by lorniu** [comment]
好吧。那等我有空也看看。

**Comment by lorniu** [comment]
请测试。

**Comment by jiacai2050** [comment]
赞，一个小问题

```
(id . "randm")
```
这个 id 要唯一的，改成用当前时间戳吧
```
(format-time-string "dupan-%s" (current-time))
```

**Comment by lorniu** [comment]
我也不知道随机和固定有啥区别。改了。

**Comment by jiacai2050** [comment]
https://stackoverflow.com/questions/2210791/json-rpc-what-is-the-id-for

就是为了配对用的，其实这里也没用到。
